
dtss += unipi_s107.dts
dtss += unipi_s117.dts
dtss += unipi_s167.dts
dtss += unipi_s167_2.dts
dtss += unipi_s207.dts
dtss += unipi_m207.dts
dtss += unipi_m527.dts
dtss += unipi_m267.dts
dtss += unipi_m267_2.dts
dtss += unipi_m567.dts
dtss += unipi_m567_2.dts
dtss += unipi_l207.dts
dtss += unipi_l527.dts
dtss += unipi_s227.dts
dtss += unipi_m537.dts


dtb-y = $(dtss:.dts=.dtb)
targets  += $(dtb-y)
always-y += $(dtb-y)