#!/bin/sh
set -e

CONFIG_NAME_A=unipi.list
CONFIG_NAME_A_OLD=unipi.old
CONFIG_NAME_B=debian-nonfree.list
CONFIG_NAME_B_OLD=debian-nonfree.old
CONFIG_ORIGINAL_LOCATION=/etc/apt/sources.list.d/

if [ -f ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_A} ]; then
  mv ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_A} ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_A_OLD}
  dpkg-divert --package divertmachine --remove --rename "${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_A}"
fi

if [ -f ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_B} ]; then
  mv ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_B} ${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_B_OLD}
  dpkg-divert --package divertmachine --remove --rename "${CONFIG_ORIGINAL_LOCATION}${CONFIG_NAME_B}"
fi

sync

#DEBHELPER#
